apiVersion: v1
kind: Service
metadata:
  name: {{ include "carx-be.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "carx-be.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "carx-be.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP

