export enum BookingStatusEnum {
  CREATED = 'CREATED',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  WAITING_FOR_PAYMENT = 'WAITING_FOR_PAYMENT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REPORTED = 'REPORTED',
  QUOTATION_SENT = 'QUOTATION_SENT',
  QUOTATION_CONFIRMED = 'QUOTATION_CONFIRMED',
}

export enum BookingActionEnum {
  BOOK_SERVICE = 'BOOK_SERVICE',
  CONFIRM_SERVICE = 'CONFIRM_SERVICE',
  SEND_SERVICE_QUOTATION = 'SEND_SERVICE_QUOTATION',
  CONFIRM_SERVICE_QUOTATION = 'CONFIRM_SERVICE_QUOTATION',
  CANCEL_SERVICE = 'CANCEL_SERVICE',
  PROCESSING_SERVICE = 'PROCESSING_SERVICE',
  COMPLETE_SERVICE = 'COMPLETE_SERVICE',
  COMPLETE_PAYMENT_SERVICE = 'COMPLETE_PAYMENT_SERVICE',
  REPORTED = 'REPORTED',
}