export enum NotificationTypeEnum {
  CARX = 'CARX',
  AGENT_CONFIRM_ORDER = 'AGENT_CONFIRM_ORDER',
  AGENT_CANCEL_ORDER = 'AGENT_CANCEL_ORDER',
  AGENT_CONFIRM_BOOKING = 'AGENT_CONFIRM_BOOKING',
  AGENT_CANCEL_BOOKING = 'AGENT_CANCEL_BOOKING',
  AGENT_RESPONSE_FLASH_BUY_REQUEST = 'AGENT_RESPONSE_FLASH_BUY_REQUEST',
  AGENT_RESPONSE_RESCUE_REQUEST = 'AGENT_RESPONSE_RESCUE_REQUEST',
  AGENT_SEND_QUOTATION = 'AGENT_SEND_QUOTATION',
  ORDER_DELIVERING = 'ORDER_DELIVERING',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  BOOKING_COMPLETED = 'BOOKING_COMPLETED',
  BOOKING_WAITING_FOR_PAYMENT= 'BOOKING_WAITING_FOR_PAYMENT',
  CUSTOMER_CREATE_ORDER = 'CUSTOMER_CREATE_ORDER',
  CUSTOMER_CANCEL_ORDER = 'CUSTOMER_CANCEL_ORDER',
  CUSTOMER_CREATE_BOOKING = 'CUSTOMER_CREATE_BOOKING',
  CUSTOMER_CANCEL_BOOKING = 'CUSTOMER_CANCEL_BOOKING',
  CUSTOMER_CREATE_FLASH_BUY_REQUEST = 'CUSTOMER_CREATE_FLASH_BUY_REQUEST',
  CUSTOMER_CREATE_RESCUE_REQUEST = 'CUSTOMER_CREATE_RESCUE_REQUEST',
  CUSTOMER_ACCEPT_FLASH_BUY_RESPONSE = 'CUSTOMER_ACCEPT_FLASH_BUY_RESPONSE',
  CUSTOMER_REPORT_ORDER = 'CUSTOMER_REPORT_ORDER',
  CUSTOMER_REPORT_BOOKING = 'CUSTOMER_REPORT_BOOKING',
  CUSTOMER_CONFIRM_QUOTATION = 'CUSTOMER_CONFIRM_QUOTATION',
  CUSTOMER_REVIEW_ORDER = 'CUSTOMER_REVIEW_ORDER',
  CUSTOMER_REVIEW_BOOKING = 'CUSTOMER_REVIEW_BOOKING',
  CUSTOMER_ACCEPT_RESCUE_RESPONSE = 'CUSTOMER_ACCEPT_RESCUE_RESPONSE',
  NEW_MESSAGE = 'NEW_MESSAGE',
  USER_LIKE_POST = 'USER_LIKE_POST',
  USER_COMMENT_POST = 'USER_COMMENT_POST',
  UPCOMING_BOOKING = 'UPCOMING_BOOKING',
  INSURANCE_CONTRACT_SUCCESSFULLY_CREATED = 'INSURANCE_CONTRACT_CREATED',
  INSURANCE_CONTRACT_CREATION_FAILED = 'INSURANCE_CONTRACT_CREATION_FAILED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
}

export enum NotificationSegmentEnum {
  CUSTOMER = 'CUSTOMER',
  AGENT = 'AGENT',
  ALL = 'ALL',
}

export enum NotificationChannelEnum {
  SMS = 'SMS',
  PUSH_NOTIFICATION = 'PUSH_NOTIFICATION',
}

export enum NotificationSendingTypeEnum {
  INSTANTLY = 'INSTANTLY',
  EVENTUALLY = 'EVENTUALLY',
}

export enum NotificationTargetGroupQueryEnum {
  CUSTOMER = 'CUSTOMER',
  AGENT = 'AGENT',
}

export enum NotificationRescueFlagEnum {
  ONSITE = 'onsite',
  TRAILER_FORMER = 'maintenance',
  TRAILER_LATER = 'trailer',
}