#name: Production Deployment CICD
#
#on:
#  push:
#    branches: [production]
#  workflow_dispatch:
#    logLevel:
#    description: 'Log level'
#    required: false
#    default: 'warning'
#    type: choice
#    options:
#      - info
#      - warning
#      - debug
#jobs:
#  build_push_deploy:
#    env:
#      DEPLOYMENT: 'carx-api'
#      IMAGE_NAME: 'eastplayers/carx-api:staigng-0.1.${{github.run_number}}'
#      CONTAINER_NAME: 'carx-api'
#      GIT_TOKEN: ${{secrets.GIT_TOKEN}}
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME}}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Setup Docker buildx
#        id: buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Build and Push Docker Image
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          context: ./
#          file: ./deployment/Dockerfile
#          builder: ${{ steps.buildx.outputs.name }}
#          push: true
#          tags: |
#            eastplayers/carx-api:staging-latest
#            ${{ env.IMAGE_NAME }}
      # - name: Commit to ops repository
      #   uses: Eastplayers/ep-gitops-action@v0.0.5
      #   with:
      #     tag: "staging-0.1.${{github.run_number}}"
