name: Production Deployment Digital Ocean

on:
  push:
    branches: [production]

jobs:
  build:
    env:
      CARX_BE_PROD: ${{ secrets.CARX_BE_PROD }}
    runs-on: [self-hosted, production]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Inject env
        run: echo "$CARX_BE_PROD" > .env
        shell: bash

      - name: Run build
        run: docker-compose build

      - name: Run up
        run: docker-compose up -d
